/*
 * File: app/view/NetworkEditorApp.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('NetworkEditor.view.NetworkEditorApp', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.panel.Panel',
        'NetworkEditor.view.GMapPanel'
    ],
    layout: 'fit',
    border: false,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'MainGMap',
                    center: {
                        lat: 42.339641,
                        lng: -71.094224
                    },
                    markers: [{
                        lat: 42.339641,
                        lng: -71.094224,
                        title: 'Boston Museum of Fine Arts',
                        listeners: {
                            click: function(e){
                                Ext.Msg.alert('It\'s fine', 'and it\'s art.');
                            }
                        }
                    },{
                        lat: 42.339419,
                        lng: -71.09077,
                        title: 'Northeastern University'
                    }]
                }
            ]
        });

        me.callParent(arguments);
    }

});